server:
  port: 8080
  servlet:
    context-path: /ofs-api

spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  security:
    user:
      name: root
      password: 123456
logging:
  file:
    name: info.created_on_%d{yyyy-MM-dd}.part_%i.log
    path: logs/demo-logback/info.created_on_%d{yyyy-MM-dd}.part_%i.log
